[project]
name = "test-util"
version = "0.1.0"
description = "Log Collection Utility for Linux and Windows Systems"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "wxpython>=4.2.3",
    "paramiko>=4.0.0",
]
